### ISSUE TITLE
Problems with Autofill / FM4000

### ISSUE THREAD

**Issue by XBarbara** [WollMux/WollMux#147]
With Wollmux 18.0.10 and LibreOffice 6.0 some Documents don't work properly. The form to write the text in does not open automatically like usual.
It seems there is a problem with the autofill function, which worked well with LibreOffice 5.2.8.0 .

**Comment by sikelerd** [comment]
I'm sorry, put we don't support Wollmux 18.0.10 with LibreOffice 6.0.

Either use LibreOffice 5.2 with WollMux 18.0.x or migrate to LibreOffice 6.1 with WollMux 18.1.x
