### ISSUE TITLE
WollMux Seriendruck als PDF-Ausgabe läuft instabil

### ISSUE THREAD

**Issue by chrlutz** [WollMux/WollMux#15]
_From [AKaw...@gmail.com](https://code.google.com/u/112647685260456810171/) on April 20, 2012 13:23:08_

Welche Schritte sind nötig, um das Problem zu reproduzieren? 1.WollMux Seriendruck aufrufen und Gesamt-PDF erzeugen lassen Was ist das erwartete Ergebnis? Was passiert stattdessen? 1.Die Funktion Drucke (PDF) stürzt nach rund 100, 200 oder 500 Teildokumenten (3-seitig) ab, gelegentlich läuft sie auch durch.
2. Ich habe direkt im Anschluß an den Absturz (kein PC-Neutstart, keine Bereinigung der TEMP-ordner) die gleichen Dateien zur Erstellung einer Gesamt-ODT-Datei benutzt(1060 Datensätze).
Dies lief fehlerfrei durch. Der odt-Zweig zeigt sich insgesamt als sehr stabil.

Welche Version des WollMux wurde verwendet?

WollMux 12.3rev2002

OpenOffice.org 3.2.1 
OOO320m19 (Build:9505)
LHM 110517001

Windows XP SP3 Bitte weitere Informationen hier angeben: Jeder Absturz hinterlässt zudem einige Hundert Temporäre PDF-dateien im Ordner (User)\Lokale Einstellungen\Temp

_Original issue: http://code.google.com/p/wollmux/issues/detail?id=15_

**Comment by sikelerd** [comment]
Die Option: Gesamtdokument (PDF) wird nicht mehr angeboten. Stattdessen soll
* Gesamtdokument (ODT) mit anschließendem export nach PDF
* oder direkt Drucken mit einem PDF-Drucker
verwendet werden.
