### ISSUE TITLE
Schmale Leiste WollMuxbar wenn WollMux  im Hintergrund ist -  Version 12.3rev2002

### ISSUE THREAD

**Issue by chrlutz** [WollMux/WollMux#16]
_From [AKaw...@gmail.com](https://code.google.com/u/112647685260456810171/) on April 20, 2012 13:30:16_

In der letzten Version die ich getestet habe (11.2?), war der WollMux lediglich als schmaler Streifen in der Bidschirmmitte zu sehen. Dies war äußerst komfortabel, da eine Ansteuerung der Standard-Windowsfensterelemente links und rechts oben (Schließen, etc.) möglich war, ohne den WollMux zu aktivieren. In der Version 12.3rev2002 nimmt er wieder fast die gesamte Bildschirmbreite ein.

_Original issue: http://code.google.com/p/wollmux/issues/detail?id=16_

**Comment by sikelerd** [comment]
Die WollMuxBar wurde abgeschafft und ist vollständig in die Sidebar von LibreOffice integriert worden.
