### ISSUE TITLE
Probleme mit dem WollMux beim Umstieg von OpenOffice 3.2.1 auf OpenOffice 3.4.1

### ISSUE THREAD

**Issue by chrlutz** [WollMux/WollMux#19]
_From [jmueller...@gmail.com](https://code.google.com/u/108050933778089543288/) on June 17, 2013 09:40:42_

Welche Schritte sind nötig, um das Problem zu reproduzieren? 1. Deinstallation WollMux 10.8
2. Deinstallation OO 3.2.1
3. Installation Apache OO 3.4.1
4. Installation WollMux 10.8

Was ist das erwartete Ergebnis?
OO 3.4.1 und WollMux ablauffähig
Was passiert stattdessen?
WollMux-Installation läuft auf Fehler.

Welche Version des WollMux wurde verwendet? 
WollMux Version 10.8

Welche Version von Openoffice.org/LibreOffice? 
alt: OpenOffice 3.2.1   
neu: Apache OO-Version 3.4.1

Welches Betriebssystem?
Windows XP Bitte weitere Informationen hier angeben: siehe anhängendes Dokument

**Attachment:** [WollMux-Problem.odt](http://code.google.com/p/wollmux/issues/detail?id=19)

_Original issue: http://code.google.com/p/wollmux/issues/detail?id=19_

**Comment by Eymux** [comment]
Nachdem der Installer mittlerweile komplett neu geschrieben wurde, betrachte ich dieses Issue als nicht mehr aktuell. Der neue Installer ab WollMux 16.04 sollte auch mit Apache Office 4 funktionieren.
