### ISSUE TITLE
A WollMux Template (Here: the Faxvorlage) loses its formatting, especially the Absenderbereich, when opened several times. 

### ISSUE THREAD

**Issue by chrlutz** [WollMux/WollMux#20]
_From [Ulrich.K...@muenchen.de](https://code.google.com/u/107907912599209337698/) on August 28, 2013 09:54:41_

Open Faxvorlage (maybe other templates as well) several times

Sometimes the template loses its formatting, the log says:

com.sun.star.uno.RuntimeException?: SwXParagraph: disposed or invalid
com.sun.star.bridges.jni_uno.JNI_proxy.dispatch_call(Native Method)
com.sun.star.bridges.jni_uno.JNI_proxy.invoke(JNI_proxy.java:175)
$Proxy63.getAnchor(Unknown Source)
de.muenchen.allg.ooo.TextDocument?.deleteParagraph(TextDocument?.java:294)
de.muenchen.allg.itd51.wollmux.DocumentCommandInterpreter?$SurroundingGarbageCollector?$ParagraphMuellmann?.tueDeinePflicht(DocumentCommandInterpreter?

WollMux version was 13.8rev2049

_Original issue: http://code.google.com/p/wollmux/issues/detail?id=20_

**Comment by smehrbrodt** [comment]
No longer reproducible with current Wollmux/LibreOffice.
