### ISSUE TITLE
Links zur Standardkonfiguration bei wollmux.org falsch

### ISSUE THREAD

**Issue by tlappe** [WollMux/WollMux#201]
Hallo zusammen,

ich wollte heute erstmals WollMux installieren. Die Installation ist mir auch gelungen, nachdem ich Java ausgewählt und unter Ubuntu 18.04 noch "libreoffice-java-common" installiert habe.

Leider finde ich die Standardkonfigurations-Datei über wollmux.org nicht, da die dortigen Links kaputt sind. Generell sind auf dieser Webseite einige Links nicht in Ordnung oder verweisen wieder auf irgendeine übergeordnete Seite von der man eigentlich gerade erst gekommen ist.

Kann mir jemand einen Link zu der Standardkonfigurations-Datei mitteilen?

Vielen Dank im Voraus.
Tim

**Comment by sikelerd** [comment]
Hallo Tim,

im Repo https://github.com/WollMux/wollmux-config findest du eine Standardkonfiguration. z.B. (https://github.com/WollMux/wollmux-config/releases/latest).

Hast du Beispiele für kaputte Links? Am besten nutzt du die Dokumentation für 18.1.

Viele Grüße
Daniel

**Comment by lauffreak** [comment]
Hallo!

ich versuche WollMux auch zum Laufen zu bekommen.
Dieser Link funktioniert nicht: https://wollmux.org/Standardkonfiguration_des_WollMux_installieren_und_pflegen

Ich habe ein anderes Problem: Beim Aufruf einer Vorlage aus dem WollMux Menü kommt eine Fehlermeldugn: Im LOG steht dann \\.wollmux\.vorlagenstandard.X.buttons70.Kurzmitteilung.ott nicht gefunden: Da ist ja gar nicht in der Standardkonfiguration.
Was kann ich machen?

GRüße
Susanne
