### ISSUE TITLE
WollMux-Mailmege: "Tabellenspalten ergänzen"-dialog should remain visible

### ISSUE THREAD

**Issue by chrlutz** [WollMux/WollMux#21]
_From [Ulrich.K...@muenchen.de](https://code.google.com/u/107907912599209337698/) on August 28, 2013 09:57:36_
1. Open for exmple "Externer Briefkopf"
2. Goto WollMux-Seriendruck
3. In the Seriendruck-Bar goto Datenquelle-> Neue Calcdatei "Tabellenspalten ergänzen"
4. In the Seriendruck-Bar goto Tabelle -> Tabellenspalten ergänzen
5. A dialog "Tabellenspalten ergänzen" is opened.
6. Switch between the writer and the calc-document several times.

desired behaviour is, every time the writer doc is in foreground, the "Tabellenspalten ergänzen"-dialog is visible too.

actual behaviour is the "Tabellenspalten ergänzen"-dialog becomes invisible after the second or third switch between writer and cal. 

WollMux version is 13.8 rev 2049, LO 3.6.4

_Original issue: http://code.google.com/p/wollmux/issues/detail?id=21_

**Comment by sikelerd** [comment]
With WollMux 18.1 mailmerge is no a sidebar and the dialogs are LibreOffice-Dialogs. So this problem doesn't exist any more.
