### ISSUE TITLE
WollMux Mailmerge 

### ISSUE THREAD

**Issue by chrlutz** [WollMux/WollMux#22]
_From [Ulrich.K...@muenchen.de](https://code.google.com/u/107907912599209337698/) on August 28, 2013 10:04:33_
1. Suppose you have a duplex-printer, which is configured to print duplex.
2. create a new writer file
3. goto WollMux-Mailmerge-> Datenquelle and select a Calc-file with
   more than an adress.
4. insert some mailmerge fields into the document
5. press "Drucken"
6. choose "Direkt drucken"
7. select the duplex printer, and press the "Properties" button of the
   printer.
8. Select Duplex->none.
9. Print

The output is double-sided, although you chose non-duplex print.

WollMux version is 13.8 rev 2049, LO 3.6.4

_Original issue: http://code.google.com/p/wollmux/issues/detail?id=22_

**Comment by sikelerd** [comment]
With WollMux 18.1 it is possible to configure the printer in use.
