### ISSUE TITLE
Wollmux LO 4.0 und LO 4.1 Probleme bei Multiuser Installation.

### ISSUE THREAD

**Issue by chrlutz** [WollMux/WollMux#23]
_From [ralf.ste...@googlemail.com](https://code.google.com/u/114451000525400904136/) on November 18, 2013 16:06:26_

Welche Schritte sind nötig, um das Problem zu reproduzieren? 1. LO 4.1 auf Citrix Xenapp 6.5HRP2 unter Win2008R2 installieren.
2. unopkg add --shared WollMux.oxt 
3. mit verschiedenen Benutzern anmelden Was ist das erwartete Ergebnis? Was passiert stattdessen? Erwartet: Die Benutzer können den WollMux unter Extras aufrufen.
Stattdessen: Der Administrator kann den WollMux aufrufen, bei allen anderen Benutzern ist der WollMux ausgegraut. Welche Version des WollMux wurde verwendet? Welche Version von Openoffice.org/LibreOffice? Welches Betriebssystem? WollMux 11.10, LO 4.0/4.1.3, Win2008R2 Bitte weitere Informationen hier angeben: Das Ergebnis von unopkg list --shared sind im Anhang als .txt -Datei.
Auffällig ist: 
  URL: vnd.sun.star.expand:$UNO_SHARED_PACKAGES_CACHE/uno_packages/lu2csra.tmp_/WollMux.oxt
  is registered: unknown
UND
      URL: vnd.sun.star.expand:$UNO_SHARED_PACKAGES_CACHE/uno_packages/lu2csra.tmp_/WollMux.oxt/WollMux.uno.jar
      is registered: no
      Media-Type: application/vnd.sun.star.uno-component;type=Java
      Description:

**Attachment:** [unopkg_admin.txt unopkg_user.txt](http://code.google.com/p/wollmux/issues/detail?id=23)

_Original issue: http://code.google.com/p/wollmux/issues/detail?id=23_

**Comment by sikelerd** [comment]
Die Installation sollte für den Multiuserbetrieb als bundled erfolgen als

`sudo unopkg add --bundled WollMux.oxt`
