### ISSUE TITLE
LO beenden im EXE-Installer unter 64-Bit Windows 7 funktioniert nicht

### ISSUE THREAD

**Issue by chrlutz** [WollMux/WollMux#25]
_From [stro...@gmail.com](https://code.google.com/u/107144244995385203948/) on October 31, 2014 15:14:40_

Welche Schritte sind nötig, um das Problem zu reproduzieren? 1.1 Bauen der TerminateOOo.jar in einer WollMux-DEV-Umgebung (ant TerminateOOo.jar)

Auf einem Windows 7 Client (64 Bit):
2.1 LibreOffice öffnen 
2.2 "java.exe -jar TerminateOOo.jar" ausführen Was ist das erwartete Ergebnis? Was passiert stattdessen? \* Erwartet Ergebnis: LibreOffice wird geschlossen
- Was passiert tatsächlich: LibreOffice bleibt offen Welche Version des WollMux wurde verwendet? Welche Version von Openoffice.org/LibreOffice? Welches Betriebssystem? \* WollMux ( Revision 2094 :635ed7ca139f)
- Libreoffice 4.1.6
- Windows 7 64 Bit Bitte weitere Informationen hier angeben: Der Fehler tritt auf, weil die unowinreg.dll aus der classes.tar.gz nur für ein 32-Bit Systeme gebaut wird (build.xml des classes-Projekt verwendet bspw. i586-mingw32msvc-g++).
  Ggf. muss auch das Build-Target "wininstaller" angepasst werden, sodass eine 32- und 64-Bit-Version gebaut werden.
- Ticket-ID intern: #13935

_Original issue: http://code.google.com/p/wollmux/issues/detail?id=25_

**Comment by sikelerd** [comment]
Den Installer wird es mit WollMux 18.2 nicht mehr geben.
