### ISSUE TITLE
Anpassung der Bootstrap.bootstrap() Parameter in WollMux

### ISSUE THREAD

**Issue by chrlutz** [WollMux/WollMux#26]
_From [juefu...@gmail.com](https://code.google.com/u/114976886145046560392/) on December 03, 2014 11:41:42_

Die Aufrufparameter waren bisher fest vorgegeben, mit umsetzung des unten aufgeführten fdo issues können und sollten sie nun konfigurierbar werden.

Mit dieser Änderung sollte es nun möglich sein folgende Parameter nicht zu setzen:
  --norestore
  --nolockcheck

siehe auch: https://bugs.freedesktop.org/show_bug.cgi?id=86784

_Original issue: http://code.google.com/p/wollmux/issues/detail?id=26_

**Comment by sikelerd** [comment]
Dieses Issue wurde mit Commit 73fd8250256103eeb1ab7360f0bf4be38c93d2be umgesetzt
