### ISSUE TITLE
Absenderliste

### ISSUE THREAD

**Issue by hkrahe** [WollMux/WollMux#268]
Hallo zusammen,

ich versuche gerade die Wollmuxversion (18.1.13.oxt mit 18.1.0-config) unetr Suse mit LO 6.1 bzw. 6.4 ans laufen zu bringen.
Grundsätzlich läuft jetzt zumindest die Sidebar, allerdings sind alle Versuche, neue Nutzer in der Absenderliste einzutragen, beim Neustart von Libreoffice mit einer überschriebenen cache.conf und einer Fehlermeldung in der wollmux.log gescheitert.

Die Fehlermeldung lautet:
2020-08-06 08:06:58 WARN  de.muenchen.all.itd51.wollmux.core ConfClassLoader:105 - ClassLoader wurde nicht konfiguriert
2020-08-06 08:05:58 ERROR de.muenchen.allg.itd51.wollmux.core.db.LocalOverrideStorageStandardImpl:156 - home/wollmux/.wollmux/cache.conf enthält korrupten Datensatz (Spalte Funktion nicht im Schema) => Cache wird ignoriert!

Java-Laufzwitumgebung ist aktiviert, das manuelle einpflegen der Spalte "Funktion" in die cache.conf hat nichts gebracht, sie wird trotzdem beim nächsten Neustart von libreoffice überschrieben. Ich komme allerdings auch gar nicht an die vordefinierte PAL-List ran. Was mache ich falsch ? In unserer alten Konfiguration (16.04) lief die cache.confvöllig problemlos.

Vielen Dank für Hilfe im Voraus.

Gruß

Holger

**Comment by sikelerd** [comment]
Hallo Holger,

WollMux 18.1.13 ist für LibreOffice 6.1 gedacht. Ob es mit LO 6.4 funktioniert kann ich nicht garantieren.

Das Schema der Datenquelle die als SENDER_SOURCE (https://wollmux.org/18.1/Konfigurationsdatei_wollmux_conf.html#sendersource) angegeben ist muss mit dem Schema in der cache.conf übereinstimmen.

Wie kann ich die Fehler reproduzieren (Bitte das Setup und die Schritte genau definieren)?

Viele Grüße
Daniel

**Comment by hkrahe** [comment]
Hallo Daniel,

vielen Dank für die schnelle Hilfe, der Hinweis auf die SENDER_SOURCE hat das Problem wohl gelöst.
Ich habe in der referat.conf definiert, dass einige Spalten der PAL, die als fehlend angemeckert wurden, hinzugefügt werden. Seitdem wird die cache.conf nicht mehr beim erneuten Öffnen von Libreoffice überschrieben bzw. neu angelegt.
Die Meldung "ClassLoader wurde nicht konfiguriert" kommt zwar weiter in der wollmux.log, scheint aber keine Auswirkungen zu haben. Ich bau jetzt mal die Sidebar und die Vorlagen nach unseren Wünschen zusammen. Mit LO 6.1 habe ich auch noch keine Probleme festgestellt, die LO 6.4 habe ich nur testweise parallel am Start, die scheint aber noch ziemlich buggy zu sein.

Dankbare Grüße

Holger

**Comment by sikelerd** [comment]
Wo setzt ihr WollMux ein?

**Comment by hkrahe** [comment]
Aktuell in der Personal- und Organisationsabteilung und die Serienbrieffunktion in einigen anderen Teilen der Verwaltung.
Wir haben nur da, wo es nicht ander geht, noch Windowsprodukte im Einsatz, ansonsten Linux und Libreoffice oder zumindest Libreoffice (Windows) statt Microsoft Office. Ich habe dieWollmuxversion 18.1.0 sowohl unter LO 6.1 als auch unter LO 6.4 ausprobiert und habe den Eindruck, dass es unter 6.4 besser läuft, obwohl die LO 6.4 durchaus noch mit Bugs behaftet ist. Unter LO 6.1 habe ich das Problem, dass mit jeder über den Wollmux geöffneten Vorlage das erste Feldbefehl-Eingabefenster aufpoppt, was ja eigentlich nicht sein sollte, dafür ist die Abfragemaske des Wollmux zuständig. Interessant auch, dass unter LO 6.1 z.B. beim Öffnen eines Briefbogen das automatische importieren der einzelnen Vorlagen zu sehen ist, während unter LO 6.4 2-3 Sekunden nichts zu sehen ist, dann öffnet der Briefbogen fix und fertig mit allen abgearbeiteten FRAG-IDs.

**Comment by sikelerd** [comment]
Gerne kannst du Tickets für die Bugs erstellen, die dir auffallen.

Hast du ein Beispieldokument, mit dem das Feldbefehl-Eingabefenster aufpoppt. Gerne auch per Mail an daniel.sikeler@muenchen.de

**Comment by sikelerd** [comment]
Gerne kannst du Tickets für die Bugs erstellen, die dir auffallen.

Hast du ein Beispieldokument, mit dem das Feldbefehl-Eingabefenster aufpoppt. Gerne auch per Mail an daniel.sikeler@muenchen.de
