### ISSUE TITLE
Stabil lauffähige Konstellation Wollmux / LibreOffice 7 / OpenJDK gesucht

### ISSUE THREAD

**Issue by support-aeksh** [WollMux/WollMux#347]
Hallo liebes Wollmux-Entwicklerteam,

die Ärztekammer Schleswig-Holstein prüft derzeit ein Update von LibreOffice 6.1.5, Wollmux 16.04 und OpenJDK 8 auf LibreOffice 7, aktuelle Wollmux Version und eine aktuelle OpenJDK Version.
Leider sind wir da immer wieder in Probleme gelaufen. Häufig crashed LibreOffice beim Neueinlesen der Feldbefehle via FormularMax 4000. 

Haben Sie da evtl. eine stabil lauffähige Kombination für uns, mit der wir Testen können?
Über sachdienliche Hinweise würden wir uns sehr freuen :-)

Viele Grüße aus dem hohen Norden und bleiben Sie gesund.
Ihre IT-Abteilung der Ärztekammer Schleswig-Holstein

**Comment by bjoernranft** [comment]
Hallo,

freut uns als Entwickler das WollMux für die Ärztekammer in Betracht ist, gerne unterstützen wir soweit es Im Rahmen der aktuellen Ressourcen möglich ist.

Aufgrund von Änderungen und einem Bug in OpenJDK 8 ist unserseits bei der LHM LibreOffice 6.4.x mit WollMux 18.2.2 und OpenJDK 11 freigegeben, die Kombination WollMux 16.04 / LO 6.1.5 / JDK 8 führt daher zu Abstürzen.
Aufgrund der Windows-Migration wird LibreOffice 7 nicht in dem Umfang bei der LHM zum Einsatz kommen, erste private Tests waren allerdings mit der Zeile darüber genannten Kombination bisher problemlos.

WollMux 18.2.2 kann hier im GIT unter Releases heruntergeladen werden.
[WollMux 18.2.2](https://github.com/WollMux/WollMux/releases/download/RELEASE_18.2.2/WollMux.oxt)

Weiterhin frohes schaffen und Gesundheit,

mfg nach Norden, das WollMux-Team.

**Comment by support-aeksh** [comment]
Vielen Dank für die Rückmeldung. 
Wir haben die geschilderten Konfigurationen (und auch noch einige weitere) ausprobiert. 
Die Vorlagen werden grundsätzlich von LibreOffice eingelesen. Beim erneuten Einlesen der Feldbefehle via Formularmax 4000 (Formular -> Wollmux Merkmale entfernen & anschließend Merkmale neu einlesen) kommt es leider zu einem sofortigem Crash von LibreOffice. Und das leider in jedweder Konfiguration von Wollmux und LO.

Gibt es ggf. Hinweise, wie wir diese Probleme vermeiden können?

**Comment by smehrbrodt** [comment]
Um welches Betriebssystem handelt es sich hier?

**Comment by smehrbrodt** [comment]
Problem kann mit LibreOffice 7.4 und aktuellem Wollmux nicht nachgestellt werden.
Bitte eine entsprechende Vorlage und Schritte zum Reproduzieren nachliefern.
