### ISSUE TITLE
Formatvorlage wird mit WM(CMD 'insertFrag' FRAG_ID 'Formate' STYLES ('TextStyles' 'NumberingStyles')) nicht überschrieben

### ISSUE THREAD

**Issue by Team310** [WollMux/WollMux#349]
Hallo,
ich habe bei mir den WollMux mit LibreOffice 6.4.7.2 unter Debian laufen. Jetzt habe ich die zentrale Formatvorlagen.ott (Formate) geändert (z. B. Formatvorlage "Datum" Schriftfarbe auf rot gesetzt)  - leider wird in dem Briefkopf.ott durch WM(CMD 'insertFrag' FRAG_ID 'Formate' STYLES ('TextStyles' 'NumberingStyles')) die vorhandene Formatvorlage nicht überschrieben. Manuell über Vorlagen->Vorlagen Laden->Aus Datei mit Überschreiben funktionierts. Dann hat die Formatvorlage "Datum" in der Briefkopf.ott die Schriftfarbe rot. 
Ich habe mir noch mal die Konfig mit den Dokumenten der LHM installiert. Auch da funktioniert es nicht mit z.B. dem Externen Briefkopf.
Was mache ich falsch?

**Comment by bjoernranft** [comment]
Hallo,

Danke für Ihren Hinweis.

Bitte prüfen ob die wollmux.conf im Pfad "/home/user/.wollmux" existiert und auf eine gültige Konfiguration (LHM) verweist.
Wenn das richtig ist sollte in der LibreOffice-Seitenleiste ein Vorlagenbaum sichtbar sein aus dem die Vorlagen geöffnet werden können.
Bitte in wollmux.conf den Log-Level auf "LOGGING_MODE "DEBUG" setzen und wollmux.log (in .wollmux) hier anhängen.

mfg

**Comment by Team310** [comment]
Hallo,
habe noch mal alles geprüft - Vorlagenbaum korrekt - Verweise korrekt
Ich lege mal noch die beiden .ott in einer Testversion (Vorlagen.zip) mit bei. 
**Brief_B.ott** ist das Vorlagendokument. Es hat zum Testen nur den Rahmen mit der Bookmark.
**Formatvorlagen.ott** enthält nur das Absatzformat "infoblock". 
Diese Formatvorlage "infoblock" soll durch Wollmux bei Generierung aus dem Vorlagenbaum in das neue Dokument einfließen bzw. eine vorhandene Formatvorlage gleichen Namens überschreiben.
Dokument aus Vorlagenbaum geöffnet -> wollmux.log beigefügt
Hab ich da irgendwie einen Denkfehler?

[wollmux.log](https://github.com/WollMux/WollMux/files/6693545/wollmux.log)
[Vorlagen.zip](https://github.com/WollMux/WollMux/files/6693609/Vorlagen.zip)

**Comment by bjoernranft** [comment]
Hallo,

danke für das Anhängen der Dokumente, da es nach einem kurzen Test funktioniert, vermute ich noch eine falsche Referenz zur FRAG_ID in der wollmux.conf, wenn möglich bitte die config auch noch anhängen.
Sollte es sich um die config der LHM handeln, bitte aufgrund von evtl. Zugangsdaten zur weiteren Hilfestellung bitte per-Email an bjoern.ranft@muenchen.de.

Der UNC-Pfad aus Ihrem Screenshot sollte bei einer lokal auf dem Dateisystem gespeicherten conf* wie folgt lauten:

_**wollmux.conf**_ 
DEFAULT_CONTEXT "file:///c:/wollmux-standalone-config/"
%include "file:///c:/wollmux-standalone-config/conf/main.conf"
%include "file:///c:/wollmux-standalone-config/conf/wollmuxbar_standard.conf"

In "wollmuxbar_standard.conf" habe ich manuell (zur Info: die WollMuxbar kann auch automatisiert durch das automux.sh Skript generiert werden) den "Brief_B.ott" und die "Formate.ott" eingetragen und die beiden Dateien in die entsprechenden Ordner kopiert. 
"Formatvorlagen.ott" habe ich in Formate.ott umbenannt damit es bei bereits referenzierten Vorlagen in der wollmux-standalone-config weiterhin "matcht", ebenso im WollMux-Kommando im Brief_B.


**_Auszug wollmuxbar_standard.conf_**

 am__standard_1_Standard_Referatsleitung(
    Elemente(
      (LABEL "Externer Briefkopf Referatsleitung" FRAG_ID "am__fragmente_Externer_Briefkopf_Referatsleitung_ott" HOTKEY "E" ACTION "openTemplate" TYPE "button" )
      (LABEL "Interner Briefkopf Referatsleitung" FRAG_ID "am__fragmente_Interner_Briefkopf_Referatsleitung_ott" HOTKEY "I" ACTION "openTemplate" TYPE "button" )
      **(LABEL "TEST_GIT" FRAG_ID "am__fragmente_test_git" HOTKEY "I" ACTION "openTemplate" TYPE "button" )**	  
    ) # Elemente
  ) # am__standard_1_Standard_Referatsleitung

...

Textfragmente(
  (FRAG_ID "am__fragmente_test_git" URL "./vorlagen/standard/./1.Standard/91.Brief_B.ott")
  (FRAG_ID "Formate" URL "./vorlagen/standard/./X.insertFrag/Formate.ott")
)

Brief_B bzw. das Label/Vorlage "TEST_GIT" wird dann nach neustart von LibreOffice im Vorlagenbaum angezeigt und bei Klick darauf geöffnet, die Formatvorlage aus Formate wird erfolgreich geladen, daher vermute ich noch einen Fehler in der Konfiguration.

Getestet habe ich mit WM 18.2.2 / LO 6.4.

Anbei der Screenshot des geöffneten Brief_B

![image](https://user-images.githubusercontent.com/29572154/122927663-62f23780-d369-11eb-960e-520f96ec4a9e.png)
