### ISSUE TITLE
Auswählbare "Themes" für das Look&Feel der WollMuxBar

### ISSUE THREAD

**Issue by chrlutz** [WollMux/WollMux#5]
_From [fa.mux2...@googlemail.com](https://code.google.com/u/114720113177938680273/) on January 27, 2012 09:59:30_

Das Look&Feel der WollMuxBar? sollte durch den Benutzer einfach nach seinen eigenen Vorlieben anpassbar sein. Es könnte eine gewisse Menge an "Themes" zur Verfügung gestellt werden, zwischen denen der Endbenutzer (optimalerweise per GUI) umschalten kann.

_Original issue: http://code.google.com/p/wollmux/issues/detail?id=5_

**Comment by sikelerd** [comment]
Die WollMuxBar wurde durch die Sidebar ersetzt und orientiert sich am LibreOffice Theme.
