### ISSUE TITLE
Button zum Maximieren von Writer-Dokument in FormularGUI

### ISSUE THREAD

**Issue by chrlutz** [WollMux/WollMux#7]
_From [fa.mux2...@googlemail.com](https://code.google.com/u/114720113177938680273/) on January 27, 2012 10:20:34_

Es wäre eventuell sinnvoll auf dem letzten Tab der FormGUI eine Schaltflaeche zu haben, 
die das Writer-Dokument maximiert und die Fomular-GUI in den Hintergrund bringt, 
damit der Benutzer das Writer-Dokument pruefen kann.

Was dagegen spricht ist mangelnder Platz in der Buttonleiste und die Tatsache, 
dass so ein Button bereits vorhanden ist, naemlich in Form des bekannten "Maximieren" Knopfes rechts oben am Writer-Fenster bzw. Doppelklick auf die Fensterzeile. 
Man könnte höchstens den Abbrechen-Knopf, auf dem letzten Tab, durch den neuen Button ersetzen. Auf den anderen Tabs muss auf jeden Fall weiter ein Abbrechen-Knopf bleiben.

_Original issue: http://code.google.com/p/wollmux/issues/detail?id=7_

**Comment by smehrbrodt** [comment]
Window management ist out of scope für Wollmux.
